### ISSUE TITLE
Product Profile - Desktop - Rating

### ISSUE THREAD

**Issue by waleedahassan** [aelshamy/ElZanqa#22]
rating stars is missing

![image](https://cloud.githubusercontent.com/assets/15191552/10794593/3a240c7e-7d9e-11e5-92bf-329cd372dbfb.png)

**Comment by aelshamy** [comment]
Working fine at my side.

**Comment by waleedahassan** [comment]
ezai tayab ya hag?
What should be done from my side, it looks as above in all devices.

**Comment by waleedahassan** [comment]
fixed in release 10.0.0.0
