### ISSUE TITLE
Store Profile - Mobile - Store Card

### ISSUE THREAD

**Issue by waleedahassan** [aelshamy/ElZanqa#28]
defacement

![img_7115 1](https://cloud.githubusercontent.com/assets/15191552/10870503/9528be1e-80d5-11e5-81b8-bb41b5717a5d.PNG)

**Comment by aelshamy** [comment]
in scope

**Comment by aelshamy** [comment]
Fixed

**Comment by waleedahassan** [comment]
are you sure you fix it.
![img_7193 1](https://cloud.githubusercontent.com/assets/15191552/11479773/5b12e3b6-979c-11e5-80a0-6c6d8c1a72a1.PNG)
