### ISSUE TITLE
Home Page - Mobile - Widgets 2

### ISSUE THREAD

**Issue by waleedahassan** [aelshamy/ElZanqa#4]
widget elements needs to be ordered as visuals (date, slider, product name,...etc)
![1](https://cloud.githubusercontent.com/assets/15191552/10646859/dc0d7052-7835-11e5-9f09-d2b0dfb55a4d.png)

**Comment by aelshamy** [comment]
as we discussed this is not an issue because of the architecture of the page for responsive design
