### ISSUE TITLE
Home Page - iPad - Header

### ISSUE THREAD

**Issue by waleedahassan** [aelshamy/ElZanqa#7]
header does not slide down or even have an arrow to slide

I clicked at user picture doesn't slide down

![image1 3](https://cloud.githubusercontent.com/assets/15191552/10648614/b0af0d12-783f-11e5-98b1-90b3384f7bc0.png)

**Comment by aelshamy** [comment]
in scope

**Comment by aelshamy** [comment]
I guess this is not the case now

**Comment by waleedahassan** [comment]
Yes, it's working, but on hover style underline shows behind avatar picture
